# Generated by Django 4.2.2 on 2023-07-05 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
